security:
    #Criptografia da senha
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

#Hierarquia de permissões
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

#Quem faz a autenticação, formulário de login
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

#Nessas URLs o usuário vai ser sempre um anônimo, para acessar /admin deve ser um ADMINISTRADOR
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/cliente/, role: ROLE_USER }