<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS2dwjlo\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS2dwjlo/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerS2dwjlo.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerS2dwjlo\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerS2dwjlo\appDevDebugProjectContainer(array(
    'container.build_hash' => 'S2dwjlo',
    'container.build_id' => '396129cc',
    'container.build_time' => 1520691604,
));
