<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2uef6jo\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2uef6jo/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2uef6jo.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2uef6jo\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container2uef6jo\appDevDebugProjectContainer(array(
    'container.build_hash' => '2uef6jo',
    'container.build_id' => '38cbab05',
    'container.build_time' => 1523105540,
));
