<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR8bzhpd\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR8bzhpd/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerR8bzhpd.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerR8bzhpd\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerR8bzhpd\appDevDebugProjectContainer(array(
    'container.build_hash' => 'R8bzhpd',
    'container.build_id' => '9ac860ae',
    'container.build_time' => 1523104629,
));
